### ISSUE TITLE
[Bug]评论区图片超出容器

### ISSUE THREAD

**Issue by XenWayne** [wehaox/Typecho-Butterfly#2]
![1](https://user-images.githubusercontent.com/54123699/151964781-9d063c81-f883-4b0d-ac76-ef3f68434233.png)
![2](https://user-images.githubusercontent.com/54123699/151964791-03b6b07f-691a-4408-abbb-01bbbfa01df9.png)
![3](https://user-images.githubusercontent.com/54123699/151964802-85d93e14-4a94-4c96-b3d2-5b4b9cc814a3.png)
如图三，在`img.entered.loading`类限制宽高均为100%后恢复正常

2022/02/11 Update:
意识到直接设置width100%不妥
通过max-width避免拉伸小图片

```css
div.comment-content p > img {
     max-width: 65%;
}
```
