### ISSUE TITLE
代码框滚动条自定义

### ISSUE THREAD

**Issue by hhowardWang** [wehaox/Typecho-Butterfly#76]
请问在文章中体现的代码框的右侧滚动条是通过哪一部分代码定义的呢？我发现其颜色是根据后台填写的自定义主要颜色，我想要自己通过css自定义，但是通过网页元素去找，没找到控制滚动条的颜色是通过什么规则定义的。

如果能进一步提供其js或php代码是在哪个文件哪一部分就更好了。

感谢！

**Comment by wehaox** [comment]
f12拉到最下面
::-webkit-scrollbar-xx 这些
不会问chatgpt吧

**Comment by hhowardWang** [comment]
找到啦，谢谢！代码如下：

```css
code::-webkit-scrollbar-thumb {
    background-color: #c0c0c0!important;
}
```
